spring:
  cloud:
    gateway:
      routes:
        - id: backend-basic
          uri: http://3.36.135.159:9999/
          predicates:
            - Path=/user/**, /health/**
#          filters:
#            - StripPrefix=2
#            - name: AuthorizationFilter